AWSTemplateFormatVersion: 2010-09-09
Description: Nested (child) template for a simple load balancer
Parameters:   # as a nested stack, these parameters will be passed in from the parent stack
  NetworkStackName:
    Description: >-
      Name of an active CloudFormation stack that contains the networking
      resources, such as the subnet and security group, that will be used in
      this stack.
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: '^[a-zA-Z][-a-zA-Z0-9]*$'
    Default: shared-network-double-subnet
Resources:
  ElasticLoadBalancer:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Name: Load-Balancer
      Scheme: internet-facing
      Subnets:
        - !ImportValue 
            'Fn::Sub': '${NetworkStackName}-Subnet1ID'
        - !ImportValue 
            'Fn::Sub': '${NetworkStackName}-Subnet2ID'
      Tags:
        - Key: Name
          Value: CloudFormation Load Balancer
Outputs:
  LoadBalancerDNS:
    Description: Public DNS For Load Balancer
    Value: !GetAtt 
      - ElasticLoadBalancer
      - DNSName
  LoadBalancerHostedZoneID:
    Description: Canonical Hosted Zone ID of load balancer.
    Value: !GetAtt 
      - ElasticLoadBalancer
      - CanonicalHostedZoneID
