AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Root Stack Template for a nested stack: Demonstrates how to implement a nested 
  stack.  This template provisions an ELB in a nested stack.   
  **WARNING** This template creates an Amazon EC2 instance. You will be billed
  for the AWS resources used if you create a stack from this template.
Parameters:
  NetworkStackName:   
    Description: >-
      Name of the CloudFormation stack that contains the networking
      resources, such as the subnet and security group, that will be used in
      this stack.
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: '^[a-zA-Z][-a-zA-Z0-9]*$'
    Default: shared-network-double-subnet  # this is the name of the shared network stack

  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the web server
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

Resources:
  LoadBalancerStack:     # this resource is defined in the nested stack
    Type: 'AWS::CloudFormation::Stack'  
    Properties:
      Parameters:    # passing the cross-stack shared resources to the nested stack
        VPC: !ImportValue 'Fn::Sub': '${NetworkStackName}-VPCID'
        PublicSubnet1: !ImportValue 'Fn::Sub': '${NetworkStackName}-Subnet1ID'
        PublicSubnet2: !ImportValue 'Fn::Sub': '${NetworkStackName}-Subnet2ID'
      TemplateURL: >-
        https://s3.amazonaws.com/cf-templates-8mxauch1fvup-us-east-1/2018271XZP-sample-nested-template.yaml

