AWSTemplateFormatVersion: 2010-09-09
  Root Stack Template for a nested stack: Demonstrates how to implement a nested 
  stack.  This template provisions an ELB in a nested stack.   
  **WARNING** This template creates an Amazon EC2 instance. You will be billed
  for the AWS resources used if you create a stack from this template.
Parameters:
  Domain:
    Type: String
    Description: Domain serviced by load balancer.
  VPC:
    Type: 'AWS::EC2::VPC::Id'
    Description: VPC for the load balancer.
  PublicSubnet1:
    Type: 'AWS::EC2::Subnet::Id'
    Description: First public subnet.
  PublicSubnet2:
    Type: 'AWS::EC2::Subnet::Id'
    Description: Second public subnet.
Resources:
  HostedZone:
    Type: 'AWS::Route53::HostedZone'
    Properties:
      Name: !Ref Domain
  HostedZoneRecords:
    Type: 'AWS::Route53::RecordSetGroup'
    Properties:
      HostedZoneId: !Ref HostedZone
      RecordSets:
        - Name: !Ref Domain
          Type: A
          AliasTarget:
            DNSName: !GetAtt 
              - LoadBalancerStack
              - Outputs.LoadBalancerDNS
            HostedZoneId: !GetAtt 
              - LoadBalancerStack
              - Outputs.LoadBalancerHostedZoneID
  LoadBalancerStack:     # this resource is defined in the nested stack
    Type: 'AWS::CloudFormation::Stack'  
    Properties:
      Parameters:    # this is where you pass the parameters above to the nested stack
        VPC: !Ref VPC
        PublicSubnet1: !Ref PublicSubnet1
        PublicSubnet2: !Ref PublicSubnet2
      TemplateURL: >-
        https://s3.amazonaws.com/cf-templates-8mxauch1fvup-us-east-1/2018271XZP-sample-nested-template.yaml
